const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);const fmt=n=>new Intl.NumberFormat('de-DE').format(Math.round(n));
const BP={
 kpis:[['950.000 €','Kapitalbedarf bis Ende Monat 24'],['Jahr 4/5','realistischer operativer Break-even'],['7,4 Mio. €','Umsatz Jahr 5'],['1,49 Mio. €','EBITDA Jahr 5']],
 problems:[['Überforderung','Finanzprodukte, ETF-Sparen und Depotprozesse wirken zu komplex.'],['Aufschieben','Sparen wird geplant, aber im Alltag nicht umgesetzt.'],['Impulskäufe','Spontane Ausgaben sabotieren langfristige Ziele.'],['fehlende Routine','Kontostände werden kontrolliert, aber nicht aktiv gesteuert.'],['geringe Startbeträge','Viele glauben, Investieren lohne sich erst später.'],['Vertrauensfrage','Finanzdaten brauchen transparente Kontrolle und klare Grenzen.']],
 flow:['Ziel wählen','Ausgaben verstehen','Sparimpuls erhalten','Betrag bestätigen','Fortschritt sehen','später über Partner investieren'],
 targets:[{t:'Lena, 22, Studentin',d:'Will sparen, aber Geld verschwindet in Alltag, Essen, Abos und Freizeit. NestEgg startet mit Notgroschen, kleinen Impulsen und einfacher Sprache.',p:['Nebenjob','kein Depot','schnelle Empfehlungen']},{t:'Max, 27, Berufseinsteiger',d:'Verdient stabil, gibt aber spontan aus und nutzt sein Depot unregelmäßig. NestEgg verbindet Konsumverhalten mit konkreten Monatszielen.',p:['erstes Vollzeitgehalt','Depot vorhanden','braucht Routine']},{t:'Sara, 31, Angestellte',d:'Hat mehrere Ziele und will Sicherheit ohne ständige Finanzplanung. NestEgg priorisiert Ziele und zeigt klare Fortschritte.',p:['Notgroschen','Urlaub','Vorsorge']}],
 mvp:[['Onboarding','Zielauswahl, Finanzverhalten, Datenschutzfreigabe'],['Open Banking','Ausgabenkategorien und Sparpotenziale über Partner'],['KI-Sparcoach','Chatbasierte Vorschläge, Erklärungen, Erinnerungen'],['Sparziele','Notgroschen, Urlaub, Umzug, Ausbildung, Altersvorsorge'],['Wochenreport','Routine-Feedback und sichtbarer Fortschritt'],['Admin/Security','Support, Einwilligungen, Datenschutzlogik']],
 markets:[['Junge Menschen','finanzielle Selbstständigkeit als starkes Ziel'],['Messenger','Alltagskanal ohne neuen Nutzungskontext'],['ETF-Sparpläne','wachsender Markt für kleine regelmäßige Beträge'],['Open Banking','datenbasierte Finanzanalyse wird praktikabler']],
 competition:[['Dimension','Bank','Neobroker','Budgeting-App','NestEgg'],['Alltagsnähe','mittel','niedrig','mittel','hoch'],['Investmentzugang','mittel','hoch','niedrig','über Partner'],['Coaching','niedrig','niedrig','mittel','hoch'],['Einstiegshürde','mittel','mittel','mittel','niedrig'],['Routinen','niedrig','niedrig','mittel','hoch']],
 revenues:[{t:'Freemium',v:'0 € Einstieg',d:'Kostenloser Einstieg zur Nutzergewinnung: Ziele, Basischeck und einfache Sparimpulse.'},{t:'Premium-Abo',v:'3,99–8,99 €/Monat',d:'Reports, Challenges, Abo-Check, Sparregeln, mehrere Ziele, Export und tiefere Analyse.'},{t:'B2B2C-Lizenzen',v:'1,50–4,00 €/aktivem Nutzer',d:'Hochschulen und Arbeitgeber zahlen für Financial-Wellbeing-Zugang. Wichtigster Skalierungshebel.'},{t:'Partner-Revenue',v:'ab Jahr 2',d:'Regulierte Partner vergüten qualifizierte Nutzeraktivierung. Vergütung bleibt transparent.'},{t:'White-Label',v:'25.000–75.000 € Setup',d:'NestEgg-Coach als Modul für Banken, Broker oder Versicherer.'},{t:'AuM-Share',v:'langfristig',d:'Zusatzumsatz aus Partner-Investmentvolumen, aber kein tragendes Frühphasenmodell.'}],
 compliance:[['Coaching Layer','Budgeting, Sparziele, Finanzbildung und Routineimpulse. Keine konkrete Wertpapierempfehlung.'],['Open-Banking Layer','Kontozugriff nur mit Einwilligung, über lizenzierten AIS-Provider, widerrufbar.'],['Investment Layer','Depot, Risikoprofil, Produktinformationen und Orderausführung über regulierte Partner.'],['Audit & Governance','Klare Trennung zwischen Bildung, Coaching und Empfehlung; KI-Guardrails.']],
 financeKpis:[['2.500','registrierte Nutzer Jahr 1'],['450.000','registrierte Nutzer Jahr 5'],['7,4 Mio. €','Umsatz Jahr 5'],['45','FTE Jahr 5']],
 assumptions:[['Kennzahl','J1','J2','J3','J4','J5'],['registrierte Nutzer','2.500','25.000','85.000','210.000','450.000'],['aktive Nutzer Ø','1.500','15.000','55.000','140.000','300.000'],['Premium-Conversion','3 %','6 %','8 %','9 %','10 %'],['zahlende B2C-Nutzer Ø','45','900','4.400','12.600','30.000'],['B2B aktive Nutzer Ø','0','5.000','22.000','55.000','125.000']],
 revenuesTable:[['Umsatzquelle','J1','J2','J3','J4','J5'],['B2C Premium','3.000 €','54.000 €','266.000 €','760.000 €','1.800.000 €'],['B2B Lizenzen','12.000 €','175.000 €','650.000 €','1.600.000 €','3.800.000 €'],['Partner-Revenue','5.000 €','42.000 €','165.000 €','560.000 €','1.350.000 €'],['Setup/White-Label','0 €','0 €','80.000 €','200.000 €','450.000 €'],['Umsatz gesamt','20.000 €','271.000 €','1.161.000 €','3.120.000 €','7.400.000 €']],
 pnl:[['Position','J1','J2','J3','J4','J5'],['Umsatz','20.000 €','271.000 €','1.161.000 €','3.120.000 €','7.400.000 €'],['Gesamtkosten','-480.000 €','-1.005.000 €','-1.790.000 €','-3.250.000 €','-5.910.000 €'],['EBITDA','-460.000 €','-734.000 €','-629.000 €','-130.000 €','1.490.000 €'],['EBITDA-Marge','-2300 %','-271 %','-54 %','-4 %','20 %']],
 funding:[['Verwendung','Betrag','Anteil'],['Produktentwicklung','260.000 €','27 %'],['Team','230.000 €','24 %'],['Marketing/Vertrieb','140.000 €','15 %'],['Compliance/Recht','120.000 €','13 %'],['Open Banking/Partner','110.000 €','12 %'],['Betrieb/Tools','45.000 €','5 %'],['Reserve','45.000 €','5 %']],
 b2c:[['Tarif','Preis','Funktionen'],['Free','0 €','Ziele, Basischeck, einfache Sparimpulse'],['Plus Student','3,99 €/Monat','Reports, Challenges, Abo-Check'],['Plus','5,99 €/Monat','alle Plus-Funktionen'],['Pro','8,99 €/Monat','tiefe Analyse, mehrere Ziele, Export']],
 b2b:[['Produkt','Preislogik','Zielkunde'],['Campus Pilot','5.000–15.000 € pauschal','Hochschulen'],['Campus License','1,50–2,50 €/aktivem Nutzer/Monat','Hochschulen'],['Employer Wellbeing','2,50–4,00 €/aktivem Nutzer/Monat','Arbeitgeber'],['Partner Integration','25.000–75.000 € Setup + Lizenz','Banken/Broker/Versicherer']],
 road:[{p:'M1–3',t:'Validierung & Partnerstruktur',g:'Klickdemo, 40–60 Interviews, Datenschutzkonzept, Legal-Mapping.',m:['Zielgruppeninterviews','Open-Banking-Provider auswählen','Partnergespräche','Pitchdeck finalisieren']},{p:'M4–9',t:'MVP & Beta',g:'Web-Onboarding, Chat-Coach, Sparzielsystem und Hochschulbeta.',m:['1.000–2.500 Nutzer','Supportprozess','Tracking der Kern-KPIs','erste Premium-Tests']},{p:'M10–18',t:'Produkt-/Marktvalidierung',g:'Premium, Open Banking, B2B-Piloten und KI-Governance.',m:['B2B-Pilot 1–3','Wochen-/Monatsreports','Conversion-Optimierung','Investmentpartner vorbereiten']},{p:'M19–30',t:'Partner-Investment',g:'Depoteröffnung, ETF-Sparplan-Weiterleitung und Partner-Revenue.',m:['Risikohinweise','Partner-KPIs','Revenue-Sharing','klare UX-Grenzen']},{p:'M31–48',t:'B2B2C-Skalierung',g:'Hochschul-/Arbeitgeberlizenzen und Break-even-Korridor.',m:['Sales-Team','Compliance-Ausbau','Automatisierung','größere B2B-Verträge']},{p:'M49–60',t:'DACH & White-Label',g:'Expansion, Enterprise-Angebote und API-Produkt.',m:['AT/CH-Prüfung','White-Label-Coach','Enterprise-Partner','optional eigene Regulierung prüfen']}],
 swot:{Strengths:['niedrige Einstiegshürde','KI + Behavioral Finance','B2B2C-Vertrieb','gute Präsentationsstory'],Weaknesses:['Vertrauen muss aufgebaut werden','begrenzte Zahlungsbereitschaft','Regulatorik komplex','Partnerabhängigkeit'],Opportunities:['ETF- und Sparplanmarkt','Financial Wellbeing','Open Banking','KI-Coaching'],Threats:['Neobroker kopieren Features','WhatsApp-Regeln ändern sich','Regulierung strenger','Datenschutzvorfall']},
 swotText:{Strengths:'Die Stärken rechtfertigen einen fokussierten Coach-first-MVP mit starker UX und Partnerarchitektur.',Weaknesses:'Die Schwächen werden durch transparente Datenkontrolle, Freemium+B2B-Modell und schlanke Partnernutzung reduziert.',Opportunities:'Die Chancen sprechen für Hochschul- und Arbeitgeberpiloten sowie spätere White-Label-Partnerschaften.',Threats:'Die Risiken machen Compliance, Plattformdiversifikation und KI-Governance zu Pflichtbestandteilen.'},
 risks:[['Risiko','Priorität','Gegenmaßnahme'],['Regulatorische Fehlpositionierung','sehr hoch','Coaching-first, Investment nur über Partner, Rechtsgutachten'],['Geringes Vertrauen in Datenfreigabe','hoch','transparente Einwilligung, Widerruf, Sicherheitskommunikation'],['Premium-Zahlungsbereitschaft gering','hoch','B2B-Lizenzen und Partnerumsätze stärken'],['B2B-Vertrieb langsamer','hoch','kleine Piloten, klare KPI-Reports'],['WhatsApp-Abhängigkeit','mittel-hoch','Web-App, E-Mail/Push und später eigene App'],['KI gibt problematische Empfehlung','hoch','Guardrails, Tests, Human Escalation, keine Renditeversprechen']],
 team:[['CEO / Business Development','Strategie, Fundraising, Partnerschaften, B2B-Vertrieb'],['CTO','Architektur, Entwicklung, Security, Skalierung'],['CPO / Product Lead','UX, Nutzerforschung, Roadmap, Conversion'],['Compliance Advisor','Regulatorik, Datenschutz, Partnerstruktur'],['Growth Lead','Marketing, Community, Hochschulakquise']],
 fte:[['Jahr','FTE','Rollen'],['Jahr 1','5','Gründerteam, Fullstack, Product/Growth, Compliance extern'],['Jahr 2','9','Backend, Data/AI, Support, B2B Sales, Marketing'],['Jahr 3','16','Sales, Compliance, Customer Success, Engineering'],['Jahr 4','28','B2B-Team, Partner Management, Data, Support'],['Jahr 5','45','DACH-Skalierung, Enterprise, Security, Operations']],
 scenarios:{J1:{active:1500,premium:3,b2b:0,partner:0,setup:0,costs:480000},J3:{active:55000,premium:8,b2b:22000,partner:12000,setup:80000,costs:1790000},J5:{active:300000,premium:10,b2b:125000,partner:100000,setup:450000,costs:5910000}},
 slides:[['Titel','NestEgg – Finanzroutinen statt Finanzstress','KI-Sparcoach für junge Menschen mit Open-Banking-Analyse und Partner-Investmentpfad.',['Coach-first','Partner-later','B2B2C']],['Problem','Das Problem ist nicht fehlende Information.','Junge Menschen wollen sparen, aber Alltag, Komplexität und Aufschub verhindern Routine.',['Impulsausgaben','zu viele Finanzinformationen','kein einfacher Start']],['Lösung','NestEgg übersetzt Finanzdaten in kleine Sparimpulse.','Der Nutzer entscheidet aktiv. Aus Impulsen werden Routinen.',['Ziel wählen','Sparfenster erkennen','Betrag bestätigen']],['Geschäftsmodell','Nicht nur AuM.','Premium, B2B2C, Partner-Revenue und White-Label machen das Modell robuster.',['Premium','B2B','Partner']],['Regulatorik','Klare Grenzen machen die Idee glaubwürdig.','NestEgg startet nicht als eigenständiger Wertpapierdienstleister.',['keine Orders im MVP','AIS-Partner','Investmentpartner']],['Finanzen','Kapitalbedarf 950.000 €, Break-even Jahr 4/5.','Jahr 5: 7,4 Mio. € Umsatz und 1,49 Mio. € EBITDA.',['24 Monate Runway','45 FTE Jahr 5','realistische Skalierung']],['Fazit','NestEgg ist der Einstieg vor dem Broker.','Das Konzept erfüllt Kundennutzen, Marktgröße, Machbarkeit, Profitabilitätslogik und Innovationsgrad.',['prüfungsstark','realistisch','skalierbar']]]
};
function table(id,rows){const el=$(id);if(!el)return;el.innerHTML=rows.map((r,i)=>`<tr>${r.map(c=>i?`<td>${c}</td>`:`<th>${c}</th>`).join('')}</tr>`).join('')}
function render(){
 $('#kpis').innerHTML=BP.kpis.map(x=>`<article class='kpi-card'><strong>${x[0]}</strong><span>${x[1]}</span></article>`).join('');
 $('#problems').innerHTML=BP.problems.map(x=>`<article class='info-card'><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
 $('#flow').innerHTML=BP.flow.map((x,i)=>`<article class='flow-card'><b>${String(i+1).padStart(2,'0')}</b><h3>${x}</h3><p>${i<5?'Coach- und Routine-Logik':'regulierter Partnerpfad'}</p></article>`).join('');
 $('#mvp').innerHTML=BP.mvp.map(x=>`<article class='info-card'><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
 $('#marketCards').innerHTML=BP.markets.map(x=>`<article class='info-card'><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
 $('#layers').innerHTML=BP.compliance.map(x=>`<article class='layer-card'><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
 $('#financeKpis').innerHTML=BP.financeKpis.map(x=>`<article class='kpi-card'><strong>${x[0]}</strong><span>${x[1]}</span></article>`).join('');
 $('#team').innerHTML=BP.team.map(x=>`<article class='info-card'><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
 table('#competition',BP.competition);table('#b2c',BP.b2c);table('#b2b',BP.b2b);table('#assumptions',BP.assumptions);table('#revenues',BP.revenuesTable);table('#pnl',BP.pnl);table('#funding',BP.funding);table('#risks',BP.risks);table('#fte',BP.fte)
}
function tabs(){let a=0;const t=$('#targetTabs'),p=$('#targetPanel');function draw(){t.innerHTML=BP.targets.map((x,i)=>`<button class='${i===a?'active':''}' data-i='${i}'>${x.t.split(',')[0]}</button>`).join('');const x=BP.targets[a];p.innerHTML=`<h3>${x.t}</h3><p>${x.d}</p><div class='pills'>${x.p.map(y=>`<span>${y}</span>`).join('')}</div>`;$$('[data-i]',t).forEach(b=>b.onclick=()=>{a=+b.dataset.i;draw()})}draw();let r=0;const rt=$('#revenueTabs'),rp=$('#revenuePanel');function drawR(){rt.innerHTML=BP.revenues.map((x,i)=>`<button class='${i===r?'active':''}' data-r='${i}'>${x.t}<br><small>${x.v}</small></button>`).join('');const x=BP.revenues[r];rp.innerHTML=`<p class='tag'>Umsatzquelle</p><h3>${x.t}</h3><strong>${x.v}</strong><p>${x.d}</p>`;$$('[data-r]',rt).forEach(b=>b.onclick=()=>{r=+b.dataset.r;drawR()})}drawR()}
function demo(){const steps=[['bot','Wähle dein erstes Ziel: Notgroschen, Ausgaben verstehen oder ETF-Sparen vorbereiten.',185],['user','Notgroschen aufbauen',185],['bot','Gute Wahl. Optional kannst du Bankdaten über einen lizenzierten Open-Banking-Partner verbinden.',185],['user','Analyse starten',185],['bot','Diese Woche sind 23 € Sparpotenzial realistisch. 23 € für dein Ziel sichern?',185],['user','23 € sichern',208],['bot','Erledigt. Dein Notgroschen wächst auf 208 €. Noch 792 € bis zum Ziel.',208]];let i=0;const chat=$('#chat');function msg(type,text){const d=document.createElement('div');d.className='msg '+type;d.textContent=text;chat.appendChild(d);chat.scrollTop=chat.scrollHeight}function stat(v){$('#saved').textContent=v+' €';$('#savedBar').style.width=Math.round(v/10)+'%';$('#savedLabel').textContent=Math.round(v/10)+' % von 1.000 €';$('#streak').textContent=i>5?'13 Tage':'12 Tage';$('#score').textContent=i>5?'87 %':'82 %'}function next(){if(i>=steps.length){i=0;chat.innerHTML=''}const s=steps[i++];msg(s[0],s[1]);stat(s[2])}$('#choices').innerHTML=['Notgroschen','Ausgaben verstehen','ETF vorbereiten'].map(x=>`<button>${x}</button>`).join('');$('#nextDemo').onclick=next;next()}
function simulator(){const sc=$('#scenarios'),ctrl=$('#controls'),res=$('#results');let state={...BP.scenarios.J3};const meta={active:['Aktive Nutzer',1000,450000,1000],premium:['Premium-Conversion',0,18,.5],b2b:['B2B-Nutzer',0,160000,1000],partner:['Partnernutzer',0,140000,1000],setup:['Setup-/White-Label',0,600000,5000],costs:['Gesamtkosten',200000,6500000,10000]};function calc(){const b2c=state.active*state.premium/100*60.36,b2b=state.b2b*30,partner=state.partner*13.75,revenue=b2c+b2b+partner+state.setup;return{b2c,b2b,partner,revenue,ebitda:revenue-state.costs,premiumUsers:state.active*state.premium/100}}function draw(){ctrl.innerHTML=Object.entries(meta).map(([k,m])=>`<div class='control'><label><span>${m[0]}</span><output>${k==='premium'?state[k]+' %':euro(state[k])}</output></label><input type='range' min='${m[1]}' max='${m[2]}' step='${m[3]}' value='${state[k]}' data-sim='${k}'></div>`).join('');$$('[data-sim]',ctrl).forEach(i=>i.oninput=()=>{state[i.dataset.sim]=+i.value;draw();drawR();mark()})}function drawR(){const r=calc();res.innerHTML=[['Zahlende Nutzer',fmt(r.premiumUsers)],['B2C Premium',euro(r.b2c)],['B2B Lizenzen',euro(r.b2b)],['Partner-Revenue',euro(r.partner)],['Umsatz gesamt',euro(r.revenue),'highlight'],['EBITDA',euro(r.ebitda),r.ebitda<0?'neg':'pos']].map(x=>`<div class='result ${x[2]||''}'><span>${x[0]}</span><b class='${x[2]||''}'>${x[1]}</b></div>`).join('')}function mark(k){$$('[data-scenario]',sc).forEach(b=>b.classList.toggle('active',b.dataset.scenario===k))}sc.innerHTML=Object.keys(BP.scenarios).map(k=>`<button data-scenario='${k}' class='${k==='J3'?'active':''}'>${k}</button>`).join('');$$('[data-scenario]',sc).forEach(b=>b.onclick=()=>{state={...BP.scenarios[b.dataset.scenario]};draw();drawR();mark(b.dataset.scenario)});draw();drawR()}
function road(){let a=1;const b=$('#roadBtns'),p=$('#roadPanel');function draw(){b.innerHTML=BP.road.map((x,i)=>`<button class='${i===a?'active':''}' data-road='${i}'><b>${x.p}</b><br>${x.t}</button>`).join('');const x=BP.road[a];p.innerHTML=`<p class='tag'>${x.p}</p><h3>${x.t}</h3><p>${x.g}</p><ul>${x.m.map(m=>`<li>${m}</li>`).join('')}</ul>`;$$('[data-road]',b).forEach(btn=>btn.onclick=()=>{a=+btn.dataset.road;draw()})}draw()}
function swot(){let a='Strengths';const g=$('#swotGrid'),t=$('#swotText');function draw(){g.innerHTML=Object.entries(BP.swot).map(([k,v])=>`<button class='${k===a?'active':''}' data-swot='${k}'><h3>${k}</h3><ul>${v.map(x=>`<li>${x}</li>`).join('')}</ul></button>`).join('');t.innerHTML=`<p class='tag'>Strategische Konsequenz</p><h3>${a}</h3><p>${BP.swotText[a]}</p>`;$$('[data-swot]',g).forEach(b=>b.onclick=()=>{a=b.dataset.swot;draw()})}draw()}
function slides(){let a=0;const st=$('#slideStage'),dots=$('#dots');function draw(){const x=BP.slides[a];st.innerHTML=`<div><p class='slide-num'>Slide ${a+1}/${BP.slides.length} · ${x[0]}</p><h3>${x[1]}</h3><p>${x[2]}</p></div><ul class='slide-points'>${x[3].map(p=>`<li>${p}</li>`).join('')}</ul>`;dots.innerHTML=BP.slides.map((_,i)=>`<button class='${i===a?'active':''}' data-dot='${i}'>${i+1}</button>`).join('');$$('[data-dot]',dots).forEach(b=>b.onclick=()=>{a=+b.dataset.dot;draw()})}$('#prevSlide').onclick=()=>{a=(a-1+BP.slides.length)%BP.slides.length;draw()};$('#nextSlide').onclick=()=>{a=(a+1)%BP.slides.length;draw()};$('[data-open-slides]').onclick=()=>go('slides');document.addEventListener('keydown',e=>{if(location.hash==='#slides'){if(e.key==='ArrowRight')$('#nextSlide').click();if(e.key==='ArrowLeft')$('#prevSlide').click()}});draw()}
function go(id){document.body.classList.add('site-open');document.body.classList.remove('is-locked');$('#app').setAttribute('aria-hidden','false');setTimeout(()=>{$('#'+id)?.scrollIntoView({behavior:'smooth'});history.replaceState(null,'','#'+id)},60)}
function nav(){ $$('[data-enter]').forEach(b=>b.onclick=()=>go(b.dataset.enter));const links=$$('.nav nav a');links.forEach(a=>a.onclick=e=>{e.preventDefault();go(a.getAttribute('href').slice(1))});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-35% 0px -55%'});$$('[data-section]').forEach(s=>io.observe(s))}
document.addEventListener('DOMContentLoaded',()=>{render();tabs();demo();simulator();road();swot();slides();nav()});